call_parentheses = "Always"
collapse_simple_statement = "Never"
column_width = 250
indent_type = "Tabs"
indent_width = 4
line_endings = "Unix"
syntax = "Luau"
quote_style = "AutoPreferDouble"

[sort_requires]
enabled = true
