[package]
name = "noahrepublic/datakeep"
description = "The final data saving solution you need"
version = "4.1.0"
license = "MIT"
authors = ["noahrepublic"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]

[dependencies]
Signal = "lucasmzreal/fastsignal@^10.3.2"
Promise = "evaera/promise@^4.0.0"

[dev-dependencies]
Iris = "sirmallard/iris@^2.3.1"
TestEZ = "roblox/testez@^0.4.1"
